### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#182]
```
TypeError: Cannot read property 'map' of undefined at file:///android_asset/www/scripts/f670d605.scripts.js:3:30067 at i (file:///android_asset/www/scripts/1a727db3.vendor.js:2:30383) at file:///android_asset/www/scripts/1a727db3.vendor.js:2:30555 at n.$eval (file:///android_asset/www/scripts/1a727db3.vendor.js:3:6168) at n.$digest (file:///android_asset/www/scripts/1a727db3.vendor.js:3:4599) at file:///android_asset/www/scripts/1a727db3.vendor.js:3:6255 at e (file:///android_asset/www/scripts/1a727db3.vendor.js:1:21107) at file:///android_asset/www/scripts/1a727db3.vendor.js:1:22538
```

**Comment by tlvince** [comment]
Almost impossible to find given the minified stack trace. Closing, but opening #198 to improve Google Analytics reports.
