### ISSUE TITLE
Cannot read property 'product_profiles' of undefined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#184]
```
TypeError: Cannot read property 'product_profiles' of undefined at get (file:///android_asset/www/scripts/f670d605.scripts.js:3:28476) at h (file:///android_asset/www/scripts/f670d605.scripts.js:3:48) at Object.k [as getBatch] (file:///android_asset/www/scripts/f670d605.scripts.js:3:598) at file:///android_asset/www/scripts/f670d605.scripts.js:3:3113 at i (file:///android_asset/www/scripts/1a727db3.vendor.js:2:30383) at file:///android_asset/www/scripts/1a727db3.vendor.js:2:30555 at n.$eval (file:///android_asset/www/scripts/1a727db3.vendor.js:3:6168) at n.$digest (file:///android_asset/www/scripts/1a727db3.vendor.js:3:4599) at n.$apply (file:///android_asset/www/scripts/1a727db3.vendor.js:3:6435) at f (file:///android_asset/www/scripts/1a727db3.vendor.js:2:13132)
```

**Comment by tlvince** [comment]
Same as #185.
