### ISSUE TITLE
Cannot read property '075bd789-4b29-4033-80b6-4f834e602628' of undefined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#185]
```
TypeError: Cannot read property '075bd789-4b29-4033-80b6-4f834e602628' of undefined at get (file:///android_asset/www/scripts/f670d605.scripts.js:3:28496) at h (file:///android_asset/www/scripts/f670d605.scripts.js:3:48) at Object.k [as getBatch] (file:///android_asset/www/scripts/f670d605.scripts.js:3:598) at file:///android_asset/www/scripts/f670d605.scripts.js:3:3113 at i (file:///android_asset/www/scripts/1a727db3.vendor.js:2:30383) at file:///android_asset/www/scripts/1a727db3.vendor.js:2:30555 at n.$eval (file:///android_asset/www/scripts/1a727db3.vendor.js:3:6168) at n.$digest (file:///android_asset/www/scripts/1a727db3.vendor.js:3:4599) at n.$apply (file:///android_asset/www/scripts/1a727db3.vendor.js:3:6435) at f (file:///android_asset/www/scripts/1a727db3.vendor.js:2:13132)
```

**Comment by tlvince** [comment]
Having a hard time reproducing this. Shelving for now.

**Comment by tlvince** [comment]
@jofomah could you take a look at this?

**Comment by tlvince** [comment]
Similar report in #184.
