### ISSUE TITLE
Cannot read property 'facility' of undefined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#186]
```
TypeError: Cannot read property 'facility' of undefined at new <anonymous> (file:///android_asset/www/scripts/f670d605.scripts.js:1:11168) at e (file:///android_asset/www/scripts/1a727db3.vendor.js:1:19172) at Object.f [as instantiate] (file:///android_asset/www/scripts/1a727db3.vendor.js:1:19264) at file:///android_asset/www/scripts/1a727db3.vendor.js:2:9406 at file:///android_asset/www/scripts/1a727db3.vendor.js:8:9294 at da (file:///android_asset/www/scripts/1a727db3.vendor.js:2:5314) at q (file:///android_asset/www/scripts/1a727db3.vendor.js:1:31335) at h (file:///android_asset/www/scripts/1a727db3.vendor.js:1:27444) at file:///android_asset/www/scripts/1a727db3.vendor.js:1:26885 at j (file:///android_asset/www/scripts/1a727db3.vendor.js:8:8537)
```

**Comment by tlvince** [comment]
Almost impossible to find given the minified stack trace. However, this has only been reported once in production and that was some months ago (mid July). Closing, but opening #198 to improve Google Analytics reports.
