### ISSUE TITLE
Cannot read property 'preloaded' of undefined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#189]
```
TypeError: Cannot read property 'preloaded' of undefined at new <anonymous> (file:///android_asset/www/scripts/controllers/app-config.js:262:19) at invoke (file:///android_asset/www/bower_components/angular/angular.js:4443:17) at Object.instantiate (file:///android_asset/www/bower_components/angular/angular.js:4451:27) at file:///android_asset/www/bower_components/angular/angular.js:9006:28 at file:///android_asset/www/bower_components/angular-ui-router/release/angular-ui-router.js:2797:28 at invokeLinkFn (file:///android_asset/www/bower_components/angular/angular.js:8642:9) at nodeLinkFn (file:///android_asset/www/bower_components/angular/angular.js:8142:11) at compositeLinkFn (file:///android_asset/www/bower_components/angular/angular.js:7534:13) at publicLinkFn (file:///android_asset/www/bower_components/angular/angular.js:7409:30) at updateView (file:///android_asset/www/bower_components/angular-ui-router/release/angular-ui-router.js:2733:23)
```

**Comment by tlvince** [comment]
Fixed by 7cecde63d923fe5214853cfccbeedf271e845583.
