### ISSUE TITLE
Report unminified stack traces to Google Analytics

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#198]
We currently receive minified stack traces in GA, which are nigh on impossible to diagnose. Investigate whether we can report unminified (source maps?).

**Comment by tlvince** [comment]
Ref https://github.com/novocaine/sourcemapped-stacktrace

**Comment by tlvince** [comment]
Sourcemaps are now included with the build. Need to test whether they get included in GA.

**Comment by tlvince** [comment]
No dice as-is:

```
I/chromium(23300): [INFO:CONSOLE(2)] "Error: tlvince-test
I/chromium(23300):     at new <anonymous> (file:///android_asset/www/scripts/scripts.3de65220.js:2:9156)
I/chromium(23300):     at e (file:///android_asset/www/scripts/vendor.848497b6.js:1:19341)
I/chromium(23300):     at Object.f [as instantiate] (file:///android_asset/www/scripts/vendor.848497b6.js:1:19433)
I/chromium(23300):     at file:///android_asset/www/scripts/vendor.848497b6.js:2:9553
I/chromium(23300):     at file:///android_asset/www/scripts/vendor.848497b6.js:8:11562
I/chromium(23300):     at ea (file:///android_asset/www/scripts/vendor.848497b6.js:2:5384)
I/chromium(23300):     at q (file:///android_asset/www/scripts/vendor.848497b6.js:1:31368)
I/chromium(23300):     at h (file:///android_asset/www/scripts/vendor.848497b6.js:1:27477)
I/chromium(23300):     at file:///android_asset/www/scripts/vendor.848497b6.js:1:26918
I/chromium(23300):     at j (file:///android_asset/www/scripts/vendor.848497b6.js:8:10805)", source: file:///android_asset/www/scripts/vendor.848497b6.js (2)
```

**Comment by tlvince** [comment]
We can apply the sourcemap to the trace via [node-source-map-support](https://github.com/evanw/node-source-map-support) to get the correct line numbers, e.g. with Coffeescript:

Before:

```
Error: foo
    at foo (script.js:7)
    at script.js:11
    at script.js:23
```

After:

```
Error: foo
    at foo (script.coffee:3)
    at script.coffee:5
    at script.coffee:1
```

Note Chrome devtools already does this for us (when sourcemaps are enabled, which it is by default), even with `console.log(error.stack)`. Dropping in node-source-map-support will enable us to get a similar output in Crosswalk, but we still don't get the original, un-mangled names. See [display source map variable names in Developer Tools](https://code.google.com/p/chromium/issues/detail?id=327092).

**Comment by tlvince** [comment]
Besides adding more moving parts to integrate node-source-map-support (which is only a partial fix), or disabling minification completely, I don't have a good solution for this. We may consider introducing a "proper" error reporting service such as Sentry or ErrorReception, however neither have offline support (as of today) hence the continuation of Google Analytics (via [angular-eha.cordova.google-analytics](https://github.com/eHealthAfrica/angular-eha.cordova.google-analytics)).
