### ISSUE TITLE
Build fails on local notification plugin

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#38]
After #37:

```
:compileArmv7DebugJava
/Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:564: error: cannot fi
nd symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
/Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:561: error: cannot fi
nd symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileArmv7DebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 4.94 secs

/Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/gradlew with args: assembleDebug,-b,/Users/tom/Projects/client/ehea
lth-africa/move/build/lomis/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-x,lint,-x,lintVitalX86Release,-x,lintVitalArmv7Release,-x,compileLint,-x,copyReleaseL
int,-x,copyDebugLint
ERROR building one of the platforms: Error: /Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /Users/tom/Projects/client/ehealth-africa/move/build/lomis/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/Users/tom/Projects/client/ehealth-africa/move/node_modules/cca/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by tlvince** [comment]
Commenting out https://github.com/eHealthAfrica/move/blob/d79cf62078058286b3967507204c9c10fc078485/scripts/build/cca-plugins.txt#L5 will workaround the issue and successfully build at least…

**Comment by karlwestin** [comment]
waiting for this PR https://github.com/katzer/cordova-plugin-local-notifications/pull/532
