### ISSUE TITLE
cordova-icon module throws errors when building

### ISSUE THREAD

**Issue by karlwestin** [eHealthAfrica/move#55]
```
 Checking Project & Icon

  ✓  platforms found: android
  ✓  icon.png exists
reading /Users/karl/Development/ehealth/move/build/lomis
  ✓  config.xml exists
Reading config file config.xml /Users/karl/Development/ehealth/move/build/lomis

 Generating Icons for android


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

My suggested solution is to get rid of this step and just handle icons the same way as Followup.. Is that ok?

**Comment by karlwestin** [comment]
was because i hadn't 
`brew install imagemagick` 
imagemagick cli tools need to be installed on the platform you're on
