### ISSUE TITLE
SyntaxError: Unexpected token o

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#79]
```
I/chromium(22935): [INFO:CONSOLE(12314)] "SyntaxError: Unexpected token o
I/chromium(22935):     at Object.parse (native)
I/chromium(22935):     at addObjectToCollection (file:///android_asset/www/scripts/services/utility.js:121:23)
I/chromium(22935):     at Scope.$scope.onProductProfileSelection (file:///android_asset/www/scripts/controllers/app-config.js:197:17)
I/chromium(22935):     at fn (eval at <anonymous> (file:///android_asset/www/bower_components/angular/angular.js:13129:15), <anonymous>:2:636)
I/chromium(22935):     at Scope.$eval (file:///android_asset/www/bower_components/angular/angular.js:15830:28)
I/chromium(22935):     at file:///android_asset/www/bower_components/angular/angular.js:22311:13
I/chromium(22935):     at file:///android_asset/www/bower_components/angular/angular.js:24990:9
I/chromium(22935):     at forEach (file:///android_asset/www/bower_components/angular/angular.js:336:20)
I/chromium(22935):     at $$writeModelToScope (file:///android_asset/www/bower_components/angular/angular.js:24988:5)
I/chromium(22935):     at writeToModelIfNeeded (file:///android_asset/www/bower_components/angular/angular.js:24981:14)", source: file:///android_asset/www/bower_compone
nts/angular/angular.js (12314)
```

**Comment by tlvince** [comment]
Resolve in https://github.com/musamusa/move/commit/52408fb97f5847fb4bb9ada8a8ae0222612c02f0.
