### ISSUE TITLE
ReferenceError: result is not defined

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/move#95]
On the last step of app config, I'm experiencing:

```
ReferenceError: result is not defined
    at afterSave (http://localhost:9000/scripts/controllers/app-config.js:475:28)
    at http://localhost:9000/scripts/controllers/app-config.js:378:13
    at processQueue (http://localhost:9000/bower_components/angular/angular.js:14551:28)
    at http://localhost:9000/bower_components/angular/angular.js:14567:27
    at Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:15830:28)
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:15641:31)
    at http://localhost:9000/bower_components/angular/angular.js:15869:26
    at completeOutstandingRequest (http://localhost:9000/bower_components/angular/angular.js:5387:10)
    at http://localhost:9000/bower_components/angular/angular.js:5659:7 undefined
```

**Comment by tlvince** [comment]
Fixed.
